name: Build and Merge

on:
  schedule:
    - cron: '0 0 * * *' # This runs the workflow every night at midnight UTC
  workflow_dispatch: # Allows manual trigger from the GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Nix
        uses: cachix/install-nix-action@v20
        with:
          nix_version: '2.7.0'

      - name: Build NixOS configuration
        run: |
          nixos-rebuild switch --flake .#mike@blade

      - name: Check build status
        run: |
          if [ $? -ne 0 ]; then exit 1; fi

  merge:
    needs: build
    if: success() # Only runs if the build step was successful
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Merge testing into main
        run: |
          git checkout main
          git merge testing --no-ff -m "Merge testing into main after successful build"
          git push origin main

